-- 0008_outreach.sql
-- One row per outbound message. Phase 1-7: nothing leaves 'pending_approval'
-- without a human action.

CREATE TABLE outreach (
    id      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    lead_id uuid NOT NULL REFERENCES leads (id) ON DELETE CASCADE,

    channel text NOT NULL DEFAULT 'email' CHECK (channel IN ('email', 'linkedin')),

    -- 1 = first touch, 2+ = follow-ups generated by WF-07.
    sequence_step smallint NOT NULL DEFAULT 1 CHECK (sequence_step BETWEEN 1 AND 5),

    subject text,
    body    text NOT NULL CHECK (length(btrim(body)) > 0),

    status text NOT NULL DEFAULT 'draft' CHECK (status IN (
        'draft',
        'pending_approval',
        'approved',
        'rejected',
        'queued',
        'sent',
        'bounced',
        'replied',
        'failed',
        'cancelled'
    )),

    approved_by      text,
    approved_at      timestamptz,
    rejection_reason text,

    provider_message_id text,
    error               text,

    sent_at    timestamptz,
    reply_at   timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT outreach_email_needs_subject
        CHECK (channel <> 'email' OR subject IS NOT NULL),
    CONSTRAINT outreach_sent_needs_timestamp
        CHECK (status <> 'sent' OR sent_at IS NOT NULL),
    CONSTRAINT outreach_approved_needs_approver
        CHECK (status <> 'approved' OR (approved_by IS NOT NULL AND approved_at IS NOT NULL)),
    CONSTRAINT outreach_reply_after_send
        CHECK (reply_at IS NULL OR sent_at IS NULL OR reply_at >= sent_at)
);

CREATE TRIGGER outreach_set_updated_at
    BEFORE UPDATE ON outreach
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE INDEX outreach_lead_id_idx ON outreach (lead_id);
CREATE INDEX outreach_status_idx  ON outreach (status);
CREATE INDEX outreach_sent_at_idx ON outreach (sent_at DESC);

-- One message per step per lead; stops duplicate follow-ups on a retry.
CREATE UNIQUE INDEX outreach_lead_step_key ON outreach (lead_id, sequence_step);

-- The approval queue and the dispatcher queue.
CREATE INDEX outreach_approval_queue_idx ON outreach (created_at)
    WHERE status = 'pending_approval';
CREATE INDEX outreach_dispatch_queue_idx ON outreach (created_at)
    WHERE status IN ('approved', 'queued');

-- Belt and braces: the suppression list is enforced in the database, not only
-- in n8n. Any insert or status change toward sending is rejected outright.
CREATE OR REPLACE FUNCTION enforce_suppression_on_outreach()
RETURNS trigger
LANGUAGE plpgsql
AS $fn$
DECLARE
    target citext;
BEGIN
    SELECT p.email
      INTO target
      FROM leads l
      JOIN people p ON p.id = l.person_id
     WHERE l.id = NEW.lead_id;

    IF target IS NOT NULL AND is_suppressed(target) THEN
        RAISE EXCEPTION 'outreach blocked: % is on the suppression list', target
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NEW;
END;
$fn$;

CREATE TRIGGER outreach_enforce_suppression
    BEFORE INSERT OR UPDATE OF status ON outreach
    FOR EACH ROW
    WHEN (NEW.status IN ('draft', 'pending_approval', 'approved', 'queued', 'sent'))
    EXECUTE FUNCTION enforce_suppression_on_outreach();
